# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 09:37
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DateVisited',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_visited', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('dates', models.ManyToManyField(through='google_maps.DateVisited', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='datevisited',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='google_maps.Location'),
        ),
        migrations.AddField(
            model_name='datevisited',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
