# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 16:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_maps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datevisited',
            name='date_visited',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 1, 8, 16, 17, 4, 794929)),
        ),
    ]
